config/routes.rb
Rails.application.routes.draw do
  resources :twitters, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end
  
  root 'twitters#index'
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content, presence: true
    validates :content, length: { in: 1..255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
before_action :set_tweet, only: [:edit, :update, :destroy]
 
  def index
   @tweets = Tweet.all
   if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
   end
  end
  
  def new
   if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end

  def create
   @tweet = Tweet.new(tweets_params)
    if @tweet.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to twitters_path, notice: "ツイートしました！"
    else
      # 入力フォームを再描画します。
      render action: 'new'
    end
  end
  
  def edit
   
  end
  
  def update
   @tweet.update(tweets_params)
   redirect_to twitters_path, notice: "ツイートを編集しました！"
  end
  
  def destroy
   @tweet.destroy
   redirect_to twitters_path, notice: "ツイートを削除しました！"
  end
  
  def confirm
    @tweet = Tweet.new(tweets_params)
    render :new if @tweet.invalid?
  end
  
  private
   def tweets_params
     params.require(:tweet).permit(:content)
   end
   
   def set_tweet
    @tweet = Tweet.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
    def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'index'
      confirm_twitters_path
    elsif action_name == 'edit'
      twitter_path
    end
  end
  
    def back_timeline
      if action_name != 'index'
        link_to "タイムラインにもどる", twitters_path 
      end
    end
    
    def tweet_placeholder
      if action_name == 'index' || action_name == 'new'
        "いまどうしてる？"
      else
        ""
      end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Twitter", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", twitters_path %></li>

        <li><%= link_to "ツイート", new_twitter_path %></li>
          
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  </header>

<%= yield %>

  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</body>
</html>

app/views/twitters/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%=  f.text_field :content, class: 'form-control', placeholder: tweet_placeholder %>
  <br>
  <%= f.submit 'ツイート', class: 'btn btn-primary btn-block' %>
<% end %>

<%= back_timeline %>

app/views/twitters/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、ツイートする。</h3>
    <%= form_for(@tweet, url: twitters_path) do |f| %>
      <%= f.hidden_field :content %>
      <p>ツイート:<%= @tweet.content %></p>
      <%= f.submit "ツイート",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@tweet, url: new_twitter_path, method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/twitters/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ツイートの編集</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/twitters/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
      <%= render 'form' %>
      <!--<%= link_to "ツイート", new_twitter_path, class: 'btn btn-default' %>-->
    <% @tweets.each do |twitter| %>
    <div class="row">
      <p><%= twitter.content %></p>
      <%= link_to "編集", edit_twitter_path(twitter.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", twitter_path(twitter.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    
    <div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
    </div>
    
    <% end %>
  </div>
</div>

app/views/twitters/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ツイート</h2>
    <%= render 'form' %>
  </div>
</div>